"""initial schema

Revision ID: 855783a81140
Revises: 
Create Date: 2026-09-15 22:59:14.416680

"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

revision: str = '855783a81140'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('generation_number', sa.Integer(), nullable=False),
    sa.Column('parent_version_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('candidate', 'active', 'retired', 'rejected', name='agent_version_status'), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_version_id'], ['agent_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('generation_number')
    )
    op.create_table('eval_set_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('eval_set_version', sa.String(length=16), nullable=False),
    sa.Column('scenario_json', sa.JSON(), nullable=False),
    sa.Column('expected_outcome_json', sa.JSON(), nullable=False),
    sa.Column('expected_tool_calls_json', sa.JSON(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('difficulty', sa.String(length=16), nullable=False),
    sa.Column('requires_hitl', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eval_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_version_id', sa.UUID(), nullable=False),
    sa.Column('eval_set_version', sa.String(length=16), nullable=False),
    sa.Column('triggered_by', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('running', 'completed', 'failed', name='eval_run_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_version_id'], ['agent_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_version_id', sa.UUID(), nullable=False),
    sa.Column('node_name', sa.String(length=64), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('diff_from_parent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_version_id'], ['agent_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_version_id', 'node_name')
    )
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=256), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('open', 'pending_approval', 'resolved', 'escalated', name='ticket_status'), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('agent_version_id', sa.UUID(), nullable=True),
    sa.Column('eval_case_id', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_version_id'], ['agent_versions.id'], ),
    sa.ForeignKeyConstraint(['eval_case_id'], ['eval_set_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cost_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=True),
    sa.Column('eval_run_id', sa.UUID(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['eval_run_id'], ['eval_runs.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('episodic_memories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eval_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('eval_run_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('resolution_correct', sa.Boolean(), nullable=False),
    sa.Column('escalation_correct', sa.Boolean(), nullable=False),
    sa.Column('tool_call_f1', sa.Float(), nullable=False),
    sa.Column('hallucination_score', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('judge_rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['eval_set_cases.id'], ),
    sa.ForeignKeyConstraint(['eval_run_id'], ['eval_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reflections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('critique_text', sa.Text(), nullable=False),
    sa.Column('proposed_lesson', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('generation_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generation_id'], ['agent_versions.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('redaction_meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool_calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=64), nullable=False),
    sa.Column('input_json', sa.JSON(), nullable=False),
    sa.Column('output_json', sa.JSON(), nullable=True),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('executed', 'pending_approval', 'rejected', name='tool_call_status'), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tool_call_id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'expired', name='approval_status'), nullable=False),
    sa.Column('action_summary', sa.Text(), nullable=False),
    sa.Column('reviewer', sa.String(length=128), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['tool_call_id'], ['tool_calls.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tool_call_id')
    )
    op.create_table('playbook_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('status', sa.Enum('draft', 'candidate', 'active', 'retired', name='playbook_status'), nullable=False),
    sa.Column('source_reflection_id', sa.UUID(), nullable=True),
    sa.Column('promoted_at', sa.DateTime(), nullable=True),
    sa.Column('promoted_by_eval_run_id', sa.UUID(), nullable=True),
    sa.Column('version_introduced', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['promoted_by_eval_run_id'], ['eval_runs.id'], ),
    sa.ForeignKeyConstraint(['source_reflection_id'], ['reflections.id'], ),
    sa.ForeignKeyConstraint(['version_introduced'], ['agent_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playbook_entries')
    op.drop_table('approvals')
    op.drop_table('tool_calls')
    op.drop_table('ticket_messages')
    op.drop_table('reflections')
    op.drop_table('feedback')
    op.drop_table('eval_results')
    op.drop_table('episodic_memories')
    op.drop_table('cost_ledger')
    op.drop_table('tickets')
    op.drop_table('prompt_versions')
    op.drop_table('eval_runs')
    op.drop_table('eval_set_cases')
    op.drop_table('agent_versions')
    # ### end Alembic commands ###
